---
title: "Advanced R"
subtitle: "Chapter 3"
output: html_notebook
---

```{r}
c(FALSE, NA)
c(FALSE, NA_integer_)
c(FALSE, NA_complex_)
c(FALSE, NA_character_)
```

```{r}
fac = factor(c('a','b','c'))
is.numeric(fac)
setNames(fac, 1:3)
unname(fac)
```

```{r}
abc = 1:5
dim(abc)
NROW(abc)
NCOL(abc)
```

These are printed differently:
```{r}
array(1:5, c(5,1,1))
array(1:5, c(1,5,1))
array(1:5, c(1,1,5))
```

Commnent is not printed
```{r}
a = 1:5
structure(a, comment = 'wow')
comment(a) = 'wow'
comment(a)
```
```{r}
b = 5:9
tab = table(a,b)
str(tab)
class(tab)
typeof(tab)
is.array(tab)
dim(tab)
dimnames(tab)
```

When levels are changed, the values are changed appropriately
```{r}
fac = factor(letters)
fac
levels(fac) = rev(levels(fac))
fac

fac = factor(1:10)
fac
levels(fac) = rev(levels(fac))
fac

rev(factor(1:10))
factor(letters, levels = rev(letters))
```
```{r}
ll = list('a', 15, FALSE)
is.vector(ll)
as.vector(ll)
unlist(ll)
```

Zero-sized DF
```{r}
a = data.frame()
a
dim(a)
```
Non-unique row names are not allowed
```{r, error=TRUE}
a = data.frame(num = 1:3, log = c(TRUE, TRUE, FALSE), chr = c('a','b','c'))
row.names(a) = c(1,1,1)
```

Data type is coerced to a common type
```{r}
t(a)
t(a[1:2])
```

data.matrix coerces to numeric:
```{r}
as.matrix(a)
data.matrix(a)
```














